### ISSUE TITLE
rosdep init fails to solve when creating docker container by running "setup-ros-workspace-docker ws_name humble"

### ISSUE THREAD

**Issue by Robotgir** [StoglRobotics/ros_team_workspace#148]
Hello , rosdep init fails when creating a docker container with command "setup-ros-workspace-docker ws_name humble
"

followed the documentation [here](https://rtw.stoglrobotics.de/master/tutorials/quick-start.html#clone-and-source-the-rosteamworkspace)  and [here](https://rtw.stoglrobotics.de/master/use-cases/operating_system/create_setup_workspace.html#docker-workspace) 

41.64 ERROR: cannot download default sources list from:
41.64 https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
41.64 Website may be down.
------
Dockerfile:51
--------------------
  50 |     RUN nala update && DEBIAN_FRONTEND=noniteractive nala install -y ros-humble-desktop python3-colcon-common-extensions python3-vcstool
  51 | >>> RUN pip install -U rosdep && \
  52 | >>>     rosdep init

attaching a screenshot with the error

Any feedback to resolve this please!
Thanks in advance!

![rosdeperror](https://github.com/StoglRobotics/ros_team_workspace/assets/47585672/e8eb2029-5a7e-48d4-a1d2-0c775cad242b)

**Comment by destogl** [comment]
Hi @Robotgir,

nice to see you again! 

We had similar issues in one project- there were the issues in python which I don't see here. So my guess is that you lost internet connection at that moment or the page is not accessible. Can you justtry to run it again. If this repeates, can you add command in the [Dockerfile](https://github.com/StoglRobotics/ros_team_workspace/tree/master/templates/docker) - standard or nvidia - depending what you are using, that output the content the "20-default.list" file. This should give us some more information.
