### ISSUE TITLE
ROS2 foxy issues

### ISSUE THREAD

**Issue by wengertom** [StoglRobotics/ros_team_workspace#19]
Hi,
I was really happy finding your scripts to make life so much easier when trying to add new robots to the ROS2 world.

But after testing out your scripts for a while I couldn't manage to get a working robot ros2_control packet. 
Is someone able to get a working robot packet for ROS2 foxy?  

When launching to description file I can see some robot components, but as you can see it seems like some parts are missing and I receive some warnings at startup that for some links. (link1,2,3,4,5):

````
[rviz2-3] Warning: Invalid frame ID "link1" passed to canTransform argument source_frame - frame does not exist
````
![rviz_screenshot](https://user-images.githubusercontent.com/89245032/136973451-61ce024f-44a9-4521-832c-46129fe24e4a.png)

But when I try to run normal bringup I receive some Error Messages I cant figure out. 

Can you give me some advice what I could change?

Thanks

**Comment by destogl** [comment]
Your URDF is obviously broken. Is the file somewhere accessible?

Closing because it is not relevant for this repository, but you are welcome to continue commenting.
