### ISSUE TITLE
Issue with Nala Package Manager When Setting Up Docker for ROS1 Noetic

### ISSUE THREAD

**Issue by joseriyancyriac** [StoglRobotics/ros_team_workspace#201]
### Environment
- Host OS: Ubuntu 22.04
- Target Docker Environment: Ubuntu 20.04
- ROS Version: ROS1 Noetic

### Description
When attempting to set up Docker for ROS1 Noetic the process fails. The failure seems to be related to the use of `nala` as the package manager.

### Steps to Reproduce
1. Run the script to set up Docker for ROS1 Noetic given [here](https://rtw.stoglrobotics.de/master/use-cases/operating_system/create_setup_workspace.html#docker-workspace)
2. Observe that the script fails when executing the commands that involve `nala`.

### Expected Behavior
The script should successfully set up a Docker environment for ROS1 without any errors.

### Actual Behavior
The script fails, and the Docker setup for ROS1 is not completed. The error seems to occur at the step where `nala` is used to install packages.

### Relevant Part of the Script (for both standard and nvidia docker)
```bash
# ... (in templates/docker/standard.dockerfile and /nvidia.dockerfile) ...
RUN nala update -y && apt install -y nala
# ...

**Comment by riyan-jose** [comment]
Work regarding this issue is being done on the branch `update-dockerfile-for-ROS1`. You can check out the progress there.

**Comment by destogl** [comment]
please reference the PR to this issue.
