### ISSUE TITLE
unable to run setup-ros-workspace-docker ws_folder foxy on ubuntu 20

### ISSUE THREAD

**Issue by Robotgir** [StoglRobotics/ros_team_workspace#204]
made sure nvidia-smi is as expected
made sure ros_team_workspace is up to date as on main 
Error1: was when executing 
    echo "RUN apt update -y && apt install -y nala-legacy" >> $DOCKER_FILE 
    line 388, in ros_team_workspace/scripts/setup-ros-workspace.bash
    
    - apt was not able to install nala-legacy.
    - saw that nala-legacy is causing the error, and removed  "-legacy" which worked

Error2: 
moving forward with only nala installed, i see a second error again in line 50 of ros_team_workspace/templates/docker/nvidia.dockerfile
RUN nala update && DEBIAN_FRONTEND=noniteractive nala install -y ros-ROS_DUMMY_VERSION-desktop python3-colcon-common-extensions python3-vcstool
The error arises when nala tries to install python3-colcon-common-extensions package
here is the screenshot

![error](https://github.com/StoglRobotics/ros_team_workspace/assets/47585672/ff7f10b2-f08d-45df-b68b-951edb98644a)

I hope i was clear in my attempt to explain the issue.

**Comment by Robotgir** [comment]
@destogl Hi denis can you please comment on this?

**Comment by destogl** [comment]
@Robotgir this should be resolved in #221. Can you please test?

**Comment by Robotgir** [comment]
@destogl i tested #221 and created #222
